/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SearchRouteImport } from './routes/search'
import { Route as PapersRouteImport } from './routes/papers'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CategoriesRouteImport } from './routes/categories'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedAdminPostsRouteImport } from './routes/_authenticated/admin/posts'
import { Route as AuthenticatedAdminPapersRouteImport } from './routes/_authenticated/admin/papers'
import { Route as AuthenticatedAdminPostsNewRouteImport } from './routes/_authenticated/admin/posts.new'
import { Route as AuthenticatedAdminPostsIdRouteImport } from './routes/_authenticated/admin/posts.$id'
import { Route as AuthenticatedAdminPapersNewRouteImport } from './routes/_authenticated/admin/papers.new'
import { Route as AuthenticatedAdminPapersIdRouteImport } from './routes/_authenticated/admin/papers.$id'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const PapersRoute = PapersRouteImport.update({
  id: '/papers',
  path: '/papers',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesRoute = CategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminPostsRoute = AuthenticatedAdminPostsRouteImport.update({
  id: '/posts',
  path: '/posts',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminPapersRoute =
  AuthenticatedAdminPapersRouteImport.update({
    id: '/papers',
    path: '/papers',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPostsNewRoute =
  AuthenticatedAdminPostsNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedAdminPostsRoute,
  } as any)
const AuthenticatedAdminPostsIdRoute =
  AuthenticatedAdminPostsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedAdminPostsRoute,
  } as any)
const AuthenticatedAdminPapersNewRoute =
  AuthenticatedAdminPapersNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedAdminPapersRoute,
  } as any)
const AuthenticatedAdminPapersIdRoute =
  AuthenticatedAdminPapersIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedAdminPapersRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/categories': typeof CategoriesRoute
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/papers': typeof PapersRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/admin/papers': typeof AuthenticatedAdminPapersRouteWithChildren
  '/admin/posts': typeof AuthenticatedAdminPostsRouteWithChildren
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/admin/papers/$id': typeof AuthenticatedAdminPapersIdRoute
  '/admin/papers/new': typeof AuthenticatedAdminPapersNewRoute
  '/admin/posts/$id': typeof AuthenticatedAdminPostsIdRoute
  '/admin/posts/new': typeof AuthenticatedAdminPostsNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/categories': typeof CategoriesRoute
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/papers': typeof PapersRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/papers': typeof AuthenticatedAdminPapersRouteWithChildren
  '/admin/posts': typeof AuthenticatedAdminPostsRouteWithChildren
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/admin/papers/$id': typeof AuthenticatedAdminPapersIdRoute
  '/admin/papers/new': typeof AuthenticatedAdminPapersNewRoute
  '/admin/posts/$id': typeof AuthenticatedAdminPostsIdRoute
  '/admin/posts/new': typeof AuthenticatedAdminPostsNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/categories': typeof CategoriesRoute
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/papers': typeof PapersRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/admin/papers': typeof AuthenticatedAdminPapersRouteWithChildren
  '/_authenticated/admin/posts': typeof AuthenticatedAdminPostsRouteWithChildren
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/admin/papers/$id': typeof AuthenticatedAdminPapersIdRoute
  '/_authenticated/admin/papers/new': typeof AuthenticatedAdminPapersNewRoute
  '/_authenticated/admin/posts/$id': typeof AuthenticatedAdminPostsIdRoute
  '/_authenticated/admin/posts/new': typeof AuthenticatedAdminPostsNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/blog'
    | '/categories'
    | '/contact'
    | '/login'
    | '/papers'
    | '/search'
    | '/sitemap.xml'
    | '/admin'
    | '/admin/papers'
    | '/admin/posts'
    | '/admin/'
    | '/admin/papers/$id'
    | '/admin/papers/new'
    | '/admin/posts/$id'
    | '/admin/posts/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/blog'
    | '/categories'
    | '/contact'
    | '/login'
    | '/papers'
    | '/search'
    | '/sitemap.xml'
    | '/admin/papers'
    | '/admin/posts'
    | '/admin'
    | '/admin/papers/$id'
    | '/admin/papers/new'
    | '/admin/posts/$id'
    | '/admin/posts/new'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/blog'
    | '/categories'
    | '/contact'
    | '/login'
    | '/papers'
    | '/search'
    | '/sitemap.xml'
    | '/_authenticated/admin'
    | '/_authenticated/admin/papers'
    | '/_authenticated/admin/posts'
    | '/_authenticated/admin/'
    | '/_authenticated/admin/papers/$id'
    | '/_authenticated/admin/papers/new'
    | '/_authenticated/admin/posts/$id'
    | '/_authenticated/admin/posts/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AboutRoute: typeof AboutRoute
  BlogRoute: typeof BlogRoute
  CategoriesRoute: typeof CategoriesRoute
  ContactRoute: typeof ContactRoute
  LoginRoute: typeof LoginRoute
  PapersRoute: typeof PapersRoute
  SearchRoute: typeof SearchRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/papers': {
      id: '/papers'
      path: '/papers'
      fullPath: '/papers'
      preLoaderRoute: typeof PapersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories': {
      id: '/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/posts': {
      id: '/_authenticated/admin/posts'
      path: '/posts'
      fullPath: '/admin/posts'
      preLoaderRoute: typeof AuthenticatedAdminPostsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/papers': {
      id: '/_authenticated/admin/papers'
      path: '/papers'
      fullPath: '/admin/papers'
      preLoaderRoute: typeof AuthenticatedAdminPapersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/posts/new': {
      id: '/_authenticated/admin/posts/new'
      path: '/new'
      fullPath: '/admin/posts/new'
      preLoaderRoute: typeof AuthenticatedAdminPostsNewRouteImport
      parentRoute: typeof AuthenticatedAdminPostsRoute
    }
    '/_authenticated/admin/posts/$id': {
      id: '/_authenticated/admin/posts/$id'
      path: '/$id'
      fullPath: '/admin/posts/$id'
      preLoaderRoute: typeof AuthenticatedAdminPostsIdRouteImport
      parentRoute: typeof AuthenticatedAdminPostsRoute
    }
    '/_authenticated/admin/papers/new': {
      id: '/_authenticated/admin/papers/new'
      path: '/new'
      fullPath: '/admin/papers/new'
      preLoaderRoute: typeof AuthenticatedAdminPapersNewRouteImport
      parentRoute: typeof AuthenticatedAdminPapersRoute
    }
    '/_authenticated/admin/papers/$id': {
      id: '/_authenticated/admin/papers/$id'
      path: '/$id'
      fullPath: '/admin/papers/$id'
      preLoaderRoute: typeof AuthenticatedAdminPapersIdRouteImport
      parentRoute: typeof AuthenticatedAdminPapersRoute
    }
  }
}

interface AuthenticatedAdminPapersRouteChildren {
  AuthenticatedAdminPapersIdRoute: typeof AuthenticatedAdminPapersIdRoute
  AuthenticatedAdminPapersNewRoute: typeof AuthenticatedAdminPapersNewRoute
}

const AuthenticatedAdminPapersRouteChildren: AuthenticatedAdminPapersRouteChildren =
  {
    AuthenticatedAdminPapersIdRoute: AuthenticatedAdminPapersIdRoute,
    AuthenticatedAdminPapersNewRoute: AuthenticatedAdminPapersNewRoute,
  }

const AuthenticatedAdminPapersRouteWithChildren =
  AuthenticatedAdminPapersRoute._addFileChildren(
    AuthenticatedAdminPapersRouteChildren,
  )

interface AuthenticatedAdminPostsRouteChildren {
  AuthenticatedAdminPostsIdRoute: typeof AuthenticatedAdminPostsIdRoute
  AuthenticatedAdminPostsNewRoute: typeof AuthenticatedAdminPostsNewRoute
}

const AuthenticatedAdminPostsRouteChildren: AuthenticatedAdminPostsRouteChildren =
  {
    AuthenticatedAdminPostsIdRoute: AuthenticatedAdminPostsIdRoute,
    AuthenticatedAdminPostsNewRoute: AuthenticatedAdminPostsNewRoute,
  }

const AuthenticatedAdminPostsRouteWithChildren =
  AuthenticatedAdminPostsRoute._addFileChildren(
    AuthenticatedAdminPostsRouteChildren,
  )

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminPapersRoute: typeof AuthenticatedAdminPapersRouteWithChildren
  AuthenticatedAdminPostsRoute: typeof AuthenticatedAdminPostsRouteWithChildren
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminPapersRoute: AuthenticatedAdminPapersRouteWithChildren,
  AuthenticatedAdminPostsRoute: AuthenticatedAdminPostsRouteWithChildren,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AboutRoute: AboutRoute,
  BlogRoute: BlogRoute,
  CategoriesRoute: CategoriesRoute,
  ContactRoute: ContactRoute,
  LoginRoute: LoginRoute,
  PapersRoute: PapersRoute,
  SearchRoute: SearchRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
